export interface PSTOpts {
  /**
   * Specify character encoding usable with `iconv-lite` package.
   * 
   * This is used to obtain unicode string from ArrayBuffer of ansiString PT_STRING8.
   * 
   * It is rare case that pst/ost files store ansiString,
   * because recent Outlook applications are Unicode based.
   * 
   * This applies to pst files generated by older versions of Outlook.
   * 
   * And {@link ansiEncoding} is required because ANSI code page depends on
   * Windows's system locale can be acquired by [GetOEMCP](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getoemcp) API.
   * 
   * OEMCP cannot be obtained from pure JavaScript environment,
   * especially on Web browser environment.
   * Thus you need to specify considered one.
   */
  ansiEncoding?: string;

  /**
   * Otherwise, you can provide your own converter (from ansiString to unicode string).
   */
  convertAnsiString?: (arrayBuffer: ArrayBuffer) => Promise<string>;
}
